export { ExtractorDeterminista, extraerReservaDeterminista } from './extractor';
export {
  canalOrigenSchema,
  extractorInputSchema,
  extraccionReservaResultadoSchema,
  fuenteDecisionSchema,
  equipajeNivelSchema,
  perfilPasajeroSchema,
  reservaExtraidaSchema,
  responsablePagoSchema,
  solicitanteTipoSchema,
  tipoVehiculoSchema,
  tipoPagoSchema,
  tipoViajeSchema,
  type CanalOrigen,
  type DireccionNormalizada,
  type EquipajeNivel,
  type ExtractorInput,
  type ExtraccionReservaResultado,
  type FuenteDecision,
  type PerfilPasajero,
  type ReservaExtraida,
  type ResponsablePago,
  type SolicitanteTipo,
  type TipoPago,
  type TipoVehiculo,
  type TipoViaje,
} from './types';
export {
  detectarAeropuerto,
  detectarTipoPago,
  extraerDni,
  extraerFechaHoraServicio,
  extraerPuntoEncuentro,
  extraerRuc,
  extraerTelefono,
  extraerVuelo,
  normalizarDireccion,
  normalizarTexto,
  validarRuc,
} from './post-procesamiento';
